apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-text-cleanup-service
  namespace: default
  labels:
    app: label-text-cleanup-service
data:
  # SPRING.DATASOURCE.URL: jdbc:mysql://service-mysql-3307/k8stextcleanupservice_db?useSSL=false
  # SPRING.DATASOURCE.USERNAME: 
  application.properties: |-
    spring.datasource.url=jdbc:mysql://service-mysql-3307/k8stextcleanupservice_db?useSSL=false
    spring.datasource.username=k8stextcleanupservice_db_user
    spring.datasource.password=
    spring.security.user.name=ashrafplanet
    spring.security.user.password=
