apiVersion: apps/v1
kind: Deployment
metadata:
  # name: mysql
  name: deployment-mysql-3307
  namespace: default
  labels:
    app: label-mysql-3307
spec:
  selector:
    matchLabels:
      app: label-mysql-3307
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: label-mysql-3307
    spec:
      containers:
      - image: mysql:8.0.31
        name: container-mysql-3307
        imagePullPolicy: IfNotPresent
        env:
        # - name: MYSQL_ROOT_PASSWORD
        #   value: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql-3307
              key: mysqlRootPassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret-mysql-3307
              key: mysqlDatabase
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-mysql-3307
              key: mysqlUser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql-3307
              key: mysqlPassword
        ports:
        - containerPort: 3307
          name: port-mysql-3307
        volumeMounts:
        - name: persistent-storage-mysql-3307
          mountPath: /var/lib/mysql
      volumes:
      - name: persistent-storage-mysql-3307
        persistentVolumeClaim:
          claimName: pvc-mysql-3307
---
apiVersion: v1
kind: Service
metadata:
  name: service-mysql-3307
  namespace: default
  labels:
    app: label-mysql-3307
spec:
  ports:
  - port: 3307
    protocol: TCP
    targetPort: 3307
  selector:
    app: label-mysql-3307
  clusterIP: None