apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql-3307
  namespace: default
  labels:
    app: label-mysql-3307
type: Opaque
# type: kubernetes.io/basic-auth
stringData:
  mysqlRootPassword: k8sroot
  mysqlDatabase: k8stextcleanupservice_db
  mysqlUser: k8stextcleanupservice_db_user
  mysqlPassword: "k8s#demo#2022#"
