apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-quick-todo-list-service
  namespace: default
  labels:
    app: label-quick-todo-list-service
data:
  # SPRING.DATASOURCE.URL: jdbc:mysql://service-mysql-3308/k8squicktodolistservice_db?useSSL=false
  # SPRING.DATASOURCE.USERNAME: 
  application.properties: |-
    spring.datasource.url=jdbc:mysql://service-mysql-3308/k8squicktodolistservice_db?useSSL=false
    spring.datasource.username=k8squicktodolistservice_db_user
    spring.datasource.password=k8s#demo#2022#
    spring.security.user.name=ashrafplanet
    spring.security.user.password=#demo#2022#
    textCleanupService.name=text-cleanup-service
    textCleanupService.url=http://text-cleanup-service:8000
    textCleanupService.credentials.username=ashrafplanet
    textCleanupService.credentials.password=#demo#2022#
    textCleanupService.credentials.authorization=Basic YXNocmFmcGxhbmV0OiNkZW1vIzIwMjIj