apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql-3308
  namespace: default
  labels:
    app: label-mysql-3308
type: Opaque
# type: kubernetes.io/basic-auth
stringData:
  mysqlRootPassword: k8sroot
  mysqlDatabase: k8squicktodolistservice_db
  mysqlUser: k8squicktodolistservice_db_user
  mysqlPassword: 
